import React from "react";
import { Col, Image, Row } from "antd";

const App: React.FC = () => (
  <div className="container-fluid mt-8 p-8">
    <Image.PreviewGroup>
      <Row gutter={[32, 32]} className="flex items-center justify-center">
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=8"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=1"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=2"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=3"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=4"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=5"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=6"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=7"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=9"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=10"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=11"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=12"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=13"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=14"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=15"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=16"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=17"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=18"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=19"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=20"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=21"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=22"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=23"
          />
        </Col>
        <Col>
          <Image
            width={250}
            src="https://source.unsplash.com/random/200x200?sig=24"
          />
        </Col>
      </Row>
    </Image.PreviewGroup>
  </div>
);

export default App;
